[build]
  base="/"
  command = "echo 'hi'"
  publish = "demo"

[[plugins]]
  package = "./src/index.js"
  [plugins.inputs]
    # required config
    checkPaths = ['/']

    # # optional config
    failWithIssues = false # true by default

    # # Developer only
    # debugMode = true # extra logging for plugin developers