[build]
  base="/"
  command = "echo 'hi'"
  publish = "demo"

[[plugins]]
  package = "./lib/index.js"
  [plugins.inputs]
    checkPaths = ['/']
    ignoreDirectories = ['thirdpost']
    ignoreElements = '.direct-link'
    failWithIssues = false # true by default
